version: '3.8'

services:
  # Application backend
  app:
    build: .
    container_name: gpyaleappback
    restart: unless-stopped
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=https://gpe-yale.edocsflow.com
      - PORT=3003
      - DB_HOST=host.docker.internal   # pour atteindre Postgres sur l'hôte
      - DB_PORT=5433                   # adapte selon ta config
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=gpe_yale
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
    extra_hosts:
      - "host.docker.internal:host-gateway" # utile sur Linux
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
