CREATE TABLE IF NOT EXISTS candidatures (
  id SERIAL PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NOT NULL,
  nationalite VARCHAR(50) NOT NULL,
  sexe VARCHAR(10) NOT NULL,
  date_naissance DATE NOT NULL,
  lieu_naissance VARCHAR(50) NOT NULL,
  telephone VARCHAR(20) NOT NULL,
  email VARCHAR(150) NOT NULL,
  organisation VARCHAR(200),
  pays VARCHAR(50) NOT NULL,
  departement VARCHAR(100),
  poste_actuel VARCHAR(100) NOT NULL,
  description_taches VARCHAR(500) NOT NULL,
  diplome VARCHAR(50) NOT NULL,
  institution VARCHAR(200) NOT NULL,
  domaine VARCHAR(100) NOT NULL,
  langues TEXT[] NOT NULL,
  niveaux JSONB NOT NULL,
  resultats_attendus VARCHAR(500) NOT NULL,
  autres_infos VARCHAR(1000),
  mode_financement VARCHAR(20) NOT NULL,
  institution_financement VARCHAR(200),
  contact_financement VARCHAR(100),
  email_contact_financement VARCHAR(150),
  source_information VARCHAR(50) NOT NULL,
  consentement BOOLEAN NOT NULL DEFAULT TRUE,
  date_soumission TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
